#pragma once
#include "targetver.h"
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdlib.h>
#include <malloc.h>
#include <memory.h>
#include <tchar.h>
#include "kursach1.h"
#include <string>
#include <fstream>
#include <windows.h>
#include <string>
#include <commdlg.h>
#include <shobjidl.h> 
#include "func.h"
#include "perem.h"
#include <Lmcons.h>
